name: state_manament_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  http: ^1.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true































